version: '2'
services:
  web:
    image: socketwench/dropwhale-web
    ports:
      - "80:80"
    volumes_from:
      - php
    depends_on:
      - php
  php:
    image: socketwench/dropwhale-php
    volumes:
      - ./.dropwhale/data/drupal:/var/www/html
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  db:
    image: socketwench/dropwhale-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
