version: '3'
services:
  web:
    image: socketwench/dropwhale-web
    ports:
      - "80:80"
    volumes:
      - .:/module
    env_file:
      - dropwhale.settings
  db:
    image: socketwench/dropwhale-db
    ports:
      - 3306:3306
    env_file:
      - dropwhale.settings
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
    env_file:
     - dropwhale.settings
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
